openapi: 3.0.0
info:
  title: delay-echo
  version: 0.0.4
paths:
  /v0.0.4/echo-header:
    post:
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: integer
                  format: int64
                  minimum: 0
              required:
              - input
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: delay-echo
        component-version: 0
        response: |-
          let input = request.body.input;
          let worker = instance("worker-static");
          let result = worker.echo("Test", 3);
          {status: input: u64, body: result}
    options:
      responses:
        default:
          description: OK
        '200':
          description: OK
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: '{access-control-allow-origin: "*", access-control-allow-methods: "GET, POST, PUT, DELETE, OPTIONS", access-control-allow-headers: "Content-Type, Authorization"}'
  /v0.0.4/echo-txt:
    post:
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
              required:
              - input
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: delay-echo
        component-version: 0
        response: |-
          let input: string = request.body.input;
          let worker = instance("worker-static");
          let result = worker.echo("Test", 3);
          {headers: {Content-Type: input, userid: "foo"}, status: 200: u64, body: result}
    options:
      responses:
        default:
          description: OK
        '200':
          description: OK
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: '{access-control-allow-origin: "*", access-control-allow-methods: "GET, POST, PUT, DELETE, OPTIONS", access-control-allow-headers: "Content-Type, Authorization"}'
  /v0.0.4/swagger-delay-variant:
    get:
      responses:
        default:
          description: OK
        '200':
          description: OK
      x-golem-api-gateway-binding:
        binding-type: swagger-ui
components: {}
x-golem-api-definition-id: delay-echo
x-golem-api-definition-version: 0.0.4
