openapi: 3.0.0
info:
  title: delay-echo
  version: 0.0.1
paths:
  /v0.0.1/delay-echo-5:
    post:
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                echo:
                  type: string
                time:
                  type: integer
                  format: int32
                  minimum: 0
              required:
              - echo
              - time
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: delay-echo
        component-version: 0
        response: |-
          let result = golem:delayecho/api.{echo}(request.body.echo, request.body.time);
          {status: 200: u64, body: result}
        worker-name: '"worker-zero"'
    options:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: object
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/swagger-delay:
    get:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: object
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: swagger-ui
  /v0.0.1/{user}/delay-echo:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: delay-echo
        component-version: 0
        response: |-
          let result = golem:delayecho/api.{echo}("Test", 3);
          {status: 200: u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "worker-${user}"
    options:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: object
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/delay-echo-2:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                echo:
                  type: string
                time:
                  type: integer
                  format: int32
                  minimum: 0
              required:
              - echo
              - time
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: delay-echo
        component-version: 0
        response: |-
          let result = golem:delayecho/api.{echo}(request.body.echo, request.body.time);
          {status: 200: u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "worker-${user}"
    options:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: object
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/{time}/delay-echo-3:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      - in: path
        name: time
        description: 'Path parameter: time'
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
        explode: false
        style: simple
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: delay-echo
        component-version: 0
        response: |-
          let user: string = request.path.user;
          let time: u32 = request.path.time;
          let result = golem:delayecho/api.{echo}("worker-${user}", time);
          {status: 200: u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "worker-${user}"
    options:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: object
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/{time}/delay-echo-4:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      - in: path
        name: time
        description: 'Path parameter: time'
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: delay-echo
        component-version: 0
        response: |-
          let time: u32 = request.path.time;
          let user: string = if time > 3: u32 then "higher" else "lower";
          let result = golem:delayecho/api.{echo}(user, time);
          {status: 200: u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "worker-${user}"
    options:
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: object
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
components: {}
x-golem-api-definition-id: delay-echo
x-golem-api-definition-version: 0.0.1
