openapi: 3.0.0
info:
  title: simple-todo-list
  version: 0.0.1
paths:
  /v0.0.1/swagger-simple:
    get:
      responses:
        default:
          description: OK
        '200':
          description: OK
      x-golem-api-gateway-binding:
        binding-type: swagger-ui
  /v0.0.1/{user}/add-simple:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  properties:
                    title:
                      type: string
                    priority:
                      type: string
                      enum:
                      - low
                      - medium
                      - high
                    deadline:
                      nullable: true
                      type: string
                  required:
                  - title
                  - priority
              required:
              - input
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        priority:
                          type: string
                          enum:
                          - low
                          - medium
                          - high
                        status:
                          type: string
                          enum:
                          - backlog
                          - in-progress
                          - done
                        created-timestamp:
                          type: integer
                          format: int64
                        updated-timestamp:
                          type: integer
                          format: int64
                        deadline:
                          nullable: true
                          type: integer
                          format: int64
                      required:
                      - id
                      - title
                      - priority
                      - status
                      - created-timestamp
                      - updated-timestamp
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        priority:
                          type: string
                          enum:
                          - low
                          - medium
                          - high
                        status:
                          type: string
                          enum:
                          - backlog
                          - in-progress
                          - done
                        created-timestamp:
                          type: integer
                          format: int64
                        updated-timestamp:
                          type: integer
                          format: int64
                        deadline:
                          nullable: true
                          type: integer
                          format: int64
                      required:
                      - id
                      - title
                      - priority
                      - status
                      - created-timestamp
                      - updated-timestamp
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let input = request.body.input;
          let result = golem:todolist/api.{add}(input);
          {status: 200: u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      responses:
        default:
          description: OK
        '200':
          description: OK
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: '{access-control-allow-origin: "*", access-control-allow-methods: "GET, POST, PUT, DELETE, OPTIONS", access-control-allow-headers: "Content-Type, Authorization"}'
  /v0.0.1/{user}/swagger:
    get:
      responses:
        default:
          description: OK
        '200':
          description: OK
      x-golem-api-gateway-binding:
        binding-type: swagger-ui
components: {}
x-golem-api-definition-id: simple-todo-list
x-golem-api-definition-version: 0.0.1
