openapi: 3.0.0
info:
  title: todo-list
  version: 0.0.1
paths:
  /v0.0.1/swagger-todo:
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: swagger-ui
  /v0.0.1/{user}/add:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  properties:
                    title:
                      type: string
                    priority:
                      type: string
                      enum:
                      - low
                      - medium
                      - high
                    deadline:
                      nullable: true
                      type: string
                  required:
                  - title
                  - priority
                  - deadline
              required:
              - input
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        priority:
                          type: string
                          enum:
                          - low
                          - medium
                          - high
                        status:
                          type: string
                          enum:
                          - backlog
                          - in-progress
                          - done
                        created-timestamp:
                          type: integer
                          format: int64
                        updated-timestamp:
                          type: integer
                          format: int64
                        deadline:
                          nullable: true
                          type: integer
                          format: int64
                      required:
                      - id
                      - title
                      - priority
                      - status
                      - created-timestamp
                      - updated-timestamp
                      - deadline
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let input = request.body.input;
          let result = golem:todolist/api.{add}(input);
          {status: 200u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/count:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: integer
                format: int32
                minimum: 0
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let result = golem:todolist/api.{count}();
          {status: 200u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/delete:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
              - id
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: string
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let id = request.body.id;
          let result = golem:todolist/api.{delete}(id);
          {status: 200u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/delete-all:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let result = golem:todolist/api.{delete-all}();
          {status: 200u64, body: "Success", headers: {Content-Type: "application/json"}}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/delete-done-items:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let result = golem:todolist/api.{delete-done-items}();
          {body: "Success", status: 200u64}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/search:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  properties:
                    keyword:
                      nullable: true
                      type: string
                    priority:
                      nullable: true
                      type: string
                      enum:
                      - low
                      - medium
                      - high
                    status:
                      nullable: true
                      type: string
                      enum:
                      - backlog
                      - in-progress
                      - done
                    deadline:
                      nullable: true
                      type: string
                    sort:
                      nullable: true
                      type: string
                      enum:
                      - priority
                      - deadline
                    limit:
                      nullable: true
                      type: integer
                      format: int32
                      minimum: 0
                  required:
                  - keyword
                  - priority
                  - status
                  - deadline
                  - sort
                  - limit
              required:
              - input
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  properties:
                    ok:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          title:
                            type: string
                          priority:
                            type: string
                            enum:
                            - low
                            - medium
                            - high
                          status:
                            type: string
                            enum:
                            - backlog
                            - in-progress
                            - done
                          created-timestamp:
                            type: integer
                            format: int64
                          updated-timestamp:
                            type: integer
                            format: int64
                          deadline:
                            nullable: true
                            type: integer
                            format: int64
                        required:
                        - id
                        - title
                        - priority
                        - status
                        - created-timestamp
                        - updated-timestamp
                        - deadline
                  required:
                  - ok
                - type: object
                  properties:
                    err:
                      type: string
                  required:
                  - err
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let input = request.body.input;
          let result = golem:todolist/api.{search}(input);
          {status: 200u64, body: result}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
  /v0.0.1/{user}/update:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                input:
                  type: object
                  properties:
                    title:
                      nullable: true
                      type: string
                    priority:
                      nullable: true
                      type: string
                      enum:
                      - low
                      - medium
                      - high
                    status:
                      nullable: true
                      type: string
                      enum:
                      - backlog
                      - in-progress
                      - done
                    deadline:
                      nullable: true
                      type: string
                  required:
                  - title
                  - priority
                  - status
                  - deadline
              required:
              - id
              - input
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: todo-list
        component-version: 0
        response: |-
          let input = request.body.input;
          let id = request.body.id;
          let result = golem:todolist/api.{update}(id, input);
          {status: 200u64, body: "Success"}
        worker-name: |-
          let user: string = request.path.user;
          "${user}"
    options:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-golem-api-gateway-binding:
        binding-type: cors-preflight
        response: |-
          {
            Access-Control-Allow-Headers: "Content-Type, Authorization",
            Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS",
            Access-Control-Allow-Origin: "*"
          }
components: {}
x-golem-api-definition-id: todo-list
x-golem-api-definition-version: 0.0.1
