openapi: 3.0.0
info:
  title: shopping-cart
  version: 0.0.2
paths:
  /v0.0.2/{user}/add-item:
    get:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
                product-id:
                  type: string
                quantity:
                  type: integer
                  format: int32
                  minimum: 0
              required:
              - name
              - price
              - product-id
              - quantity
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: string
                  status:
                    type: integer
                    format: int64
                    minimum: 0
                required:
                - body
                - status
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: shopping-echo
        component-version: 0
        response: |-
          let quantity: u32 = request.body.quantity;
          let product_id: string = request.body.product-id;
          let name: string = request.body.name;
          let price: f32 = request.body.price;
          let input = {name: name, product-id: product_id, price: price, quantity: quantity};
          let result = golem:shoppingcart/api.{add-item}(input);
          {status: 200u64, body: "Item added"}
        worker-name: |-
          let user: string = request.path.user;
          "worker-${user}"
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: object
                  properties:
                    product-id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                      format: float
                    quantity:
                      type: integer
                      format: int32
                      minimum: 0
                  required:
                  - product-id
                  - name
                  - price
                  - quantity
              required:
              - item
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: string
                  status:
                    type: integer
                    format: int64
                    minimum: 0
                required:
                - body
                - status
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: shopping-echo
        component-version: 0
        response: |-
          let item = request.body.item;
          let result = golem:shoppingcart/api.{add-item}(item);
          {status: 200u64, body: "Item added"}
        worker-name: |-
          let user: string = request.path.user;
          "worker-${user}"
    delete:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: string
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: object
                  properties:
                    product-id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                      format: float
                    quantity:
                      type: integer
                      format: int32
                      minimum: 0
                  required:
                  - product-id
                  - name
                  - price
                  - quantity
              required:
              - item
        required: true
      responses:
        '204':
          description: No Content
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: shopping-echo
        component-version: 0
        response: |-
          let item = request.body.item;
          let result = golem:shoppingcart/api.{add-item}(item);
          {status: 200u64, body: "Item added"}
        worker-name: |-
          let user: string = request.path.user;
          "worker-${user}"
components: {}
x-golem-api-definition-id: shopping-cart
x-golem-api-definition-version: 0.0.2
