openapi: 3.0.0
info:
  title: shopping-cart
  version: 0.0.1
paths:
  /v1/{user}/add-to-cart:
    post:
      parameters:
      - in: path
        name: user
        description: 'Path parameter: user'
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
        explode: false
        style: simple
      requestBody:
        description: Request payload
        content:
          application/json:
            schema:
              type: object
              properties:
                product-id:
                  type: string
                name:
                  type: string
                price:
                  type: number
                  format: float
                quantity:
                  type: integer
                  format: int32
                  minimum: 0
              required:
              - product-id
              - name
              - price
              - quantity
        required: true
      responses:
        default:
          description: Created
          content:
            application/json:
              schema:
                type: string
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
      x-golem-api-gateway-binding:
        binding-type: default
        component-name: swaggerui:shopping-cart
        component-version: 0
        response: |-
          let user: u32 = request.path.user;
          let worker = instance("cart-${user}");
          worker.add-item(request.body);
          "successfully added item to cart"
components: {}
x-golem-api-definition-id: shopping-cart
x-golem-api-definition-version: 0.0.1
